### ISSUE TITLE
Expected a string value

### ISSUE THREAD

**Issue by liamstory** [mirumee/saleor-dashboard#295]
![스크린샷 2019-12-06 오후 11 13 21](https://user-images.githubusercontent.com/20754969/70329188-22fa5b00-187e-11ea-825e-38a73f685701.png)
when I login dashboard by admin@example.com and password admin

webpage show me "Saleor ran into an unexpected problem" 

and saleor server show me

```
ERROR saleor.graphql.errors.unhandled A query failed unexpectedly [PID:8041:Thread-2]
Traceback (most recent call last):
  File "/Users/hyungryulpark/.local/share/virtualenvs/saleor-sshahpr1/lib/python3.7/site-packages/promise/promise.py", line 487, in _resolve_from_executor
    executor(resolve, reject)
  File "/Users/hyungryulpark/.local/share/virtualenvs/saleor-sshahpr1/lib/python3.7/site-packages/promise/promise.py", line 754, in executor
    return resolve(f(*args, **kwargs))
  File "/Users/hyungryulpark/.local/share/virtualenvs/saleor-sshahpr1/lib/python3.7/site-packages/graphql/execution/middleware.py", line 75, in make_it_promise
    return next(*args, **kwargs)
  File "/Users/hyungryulpark/Desktop/saleor/saleor/graphql/core/mutations.py", line 593, in mutate
    result = super().mutate(root, info, **kwargs)
  File "/Users/hyungryulpark/.local/share/virtualenvs/saleor-sshahpr1/lib/python3.7/site-packages/graphql_jwt/decorators.py", line 106, in wrapper
    result = f(cls, root, info, **kwargs)
  File "/Users/hyungryulpark/.local/share/virtualenvs/saleor-sshahpr1/lib/python3.7/site-packages/graphql_jwt/decorators.py", line 99, in wrapper
    return on_resolve(values)
  File "/Users/hyungryulpark/.local/share/virtualenvs/saleor-sshahpr1/lib/python3.7/site-packages/graphql_jwt/decorators.py", line 72, in on_resolve
    payload.token = get_token(user, info.context)
  File "/Users/hyungryulpark/.local/share/virtualenvs/saleor-sshahpr1/lib/python3.7/site-packages/graphql_jwt/shortcuts.py", line 16, in get_token
    return jwt_settings.JWT_ENCODE_HANDLER(payload, context)
  File "/Users/hyungryulpark/.local/share/virtualenvs/saleor-sshahpr1/lib/python3.7/site-packages/graphql_jwt/utils.py", line 40, in jwt_encode
    jwt_settings.JWT_ALGORITHM,
  File "/Users/hyungryulpark/.local/share/virtualenvs/saleor-sshahpr1/lib/python3.7/site-packages/jwt/api_jwt.py", line 65, in encode
    json_payload, key, algorithm, headers, json_encoder
  File "/Users/hyungryulpark/.local/share/virtualenvs/saleor-sshahpr1/lib/python3.7/site-packages/jwt/api_jws.py", line 113, in encode
    key = alg_obj.prepare_key(key)
  File "/Users/hyungryulpark/.local/share/virtualenvs/saleor-sshahpr1/lib/python3.7/site-packages/jwt/algorithms.py", line 140, in prepare_key
    key = force_bytes(key)
  File "/Users/hyungryulpark/.local/share/virtualenvs/saleor-sshahpr1/lib/python3.7/site-packages/jwt/utils.py", line 30, in force_bytes
    raise TypeError('Expected a string value')
TypeError: Expected a string value
ERROR saleor.graphql.errors.unhandled A query failed unexpectedly [PID:8041:Thread-2]
Traceback (most recent call last):
  File "/Users/hyungryulpark/.local/share/virtualenvs/saleor-sshahpr1/lib/python3.7/site-packages/promise/promise.py", line 487, in _resolve_from_executor
    executor(resolve, reject)
  File "/Users/hyungryulpark/.local/share/virtualenvs/saleor-sshahpr1/lib/python3.7/site-packages/promise/promise.py", line 754, in executor
    return resolve(f(*args, **kwargs))
  File "/Users/hyungryulpark/.local/share/virtualenvs/saleor-sshahpr1/lib/python3.7/site-packages/graphql/execution/middleware.py", line 75, in make_it_promise
    return next(*args, **kwargs)
  File "/Users/hyungryulpark/Desktop/saleor/saleor/graphql/core/mutations.py", line 593, in mutate
    result = super().mutate(root, info, **kwargs)
  File "/Users/hyungryulpark/.local/share/virtualenvs/saleor-sshahpr1/lib/python3.7/site-packages/graphql_jwt/decorators.py", line 106, in wrapper
    result = f(cls, root, info, **kwargs)
  File "/Users/hyungryulpark/.local/share/virtualenvs/saleor-sshahpr1/lib/python3.7/site-packages/graphql_jwt/decorators.py", line 99, in wrapper
    return on_resolve(values)
  File "/Users/hyungryulpark/.local/share/virtualenvs/saleor-sshahpr1/lib/python3.7/site-packages/graphql_jwt/decorators.py", line 72, in on_resolve
    payload.token = get_token(user, info.context)
  File "/Users/hyungryulpark/.local/share/virtualenvs/saleor-sshahpr1/lib/python3.7/site-packages/graphql_jwt/shortcuts.py", line 16, in get_token
    return jwt_settings.JWT_ENCODE_HANDLER(payload, context)
  File "/Users/hyungryulpark/.local/share/virtualenvs/saleor-sshahpr1/lib/python3.7/site-packages/graphql_jwt/utils.py", line 40, in jwt_encode
    jwt_settings.JWT_ALGORITHM,
  File "/Users/hyungryulpark/.local/share/virtualenvs/saleor-sshahpr1/lib/python3.7/site-packages/jwt/api_jwt.py", line 65, in encode
    json_payload, key, algorithm, headers, json_encoder
  File "/Users/hyungryulpark/.local/share/virtualenvs/saleor-sshahpr1/lib/python3.7/site-packages/jwt/api_jws.py", line 113, in encode
    key = alg_obj.prepare_key(key)
  File "/Users/hyungryulpark/.local/share/virtualenvs/saleor-sshahpr1/lib/python3.7/site-packages/jwt/algorithms.py", line 140, in prepare_key
    key = force_bytes(key)
  File "/Users/hyungryulpark/.local/share/virtualenvs/saleor-sshahpr1/lib/python3.7/site-packages/jwt/utils.py", line 30, in force_bytes
    raise TypeError('Expected a string value')
TypeError: Expected a string value
ERROR saleor.graphql.errors.unhandled A query failed unexpectedly [PID:8041:Thread-2]
Traceback (most recent call last):
  File "/Users/hyungryulpark/.local/share/virtualenvs/saleor-sshahpr1/lib/python3.7/site-packages/promise/promise.py", line 487, in _resolve_from_executor
    executor(resolve, reject)
  File "/Users/hyungryulpark/.local/share/virtualenvs/saleor-sshahpr1/lib/python3.7/site-packages/promise/promise.py", line 754, in executor
    return resolve(f(*args, **kwargs))
  File "/Users/hyungryulpark/.local/share/virtualenvs/saleor-sshahpr1/lib/python3.7/site-packages/graphql/execution/middleware.py", line 75, in make_it_promise
    return next(*args, **kwargs)
  File "/Users/hyungryulpark/Desktop/saleor/saleor/graphql/core/mutations.py", line 593, in mutate
    result = super().mutate(root, info, **kwargs)
  File "/Users/hyungryulpark/.local/share/virtualenvs/saleor-sshahpr1/lib/python3.7/site-packages/graphql_jwt/decorators.py", line 106, in wrapper
    result = f(cls, root, info, **kwargs)
  File "/Users/hyungryulpark/.local/share/virtualenvs/saleor-sshahpr1/lib/python3.7/site-packages/graphql_jwt/decorators.py", line 99, in wrapper
    return on_resolve(values)
  File "/Users/hyungryulpark/.local/share/virtualenvs/saleor-sshahpr1/lib/python3.7/site-packages/graphql_jwt/decorators.py", line 72, in on_resolve
    payload.token = get_token(user, info.context)
  File "/Users/hyungryulpark/.local/share/virtualenvs/saleor-sshahpr1/lib/python3.7/site-packages/graphql_jwt/shortcuts.py", line 16, in get_token
    return jwt_settings.JWT_ENCODE_HANDLER(payload, context)
  File "/Users/hyungryulpark/.local/share/virtualenvs/saleor-sshahpr1/lib/python3.7/site-packages/graphql_jwt/utils.py", line 40, in jwt_encode
    jwt_settings.JWT_ALGORITHM,
  File "/Users/hyungryulpark/.local/share/virtualenvs/saleor-sshahpr1/lib/python3.7/site-packages/jwt/api_jwt.py", line 65, in encode
    json_payload, key, algorithm, headers, json_encoder
  File "/Users/hyungryulpark/.local/share/virtualenvs/saleor-sshahpr1/lib/python3.7/site-packages/jwt/api_jws.py", line 113, in encode
    key = alg_obj.prepare_key(key)
  File "/Users/hyungryulpark/.local/share/virtualenvs/saleor-sshahpr1/lib/python3.7/site-packages/jwt/algorithms.py", line 140, in prepare_key
    key = force_bytes(key)
  File "/Users/hyungryulpark/.local/share/virtualenvs/saleor-sshahpr1/lib/python3.7/site-packages/jwt/utils.py", line 30, in force_bytes
    raise TypeError('Expected a string value')
TypeError: Expected a string value
```

**Comment by karolkielecki** [comment]
@liamstory Hi there! I'm very sorry for my late reply. Did you setup up environment variables? Please take a look here: https://github.com/mirumee/saleor-dashboard#configuration

If you still cannot login to your dashboard, please let me know.
Best
